### PR TITLE
Feature/wifi hotspot

### PR DESCRIPTION
**Pull request by anuejn**

### CODE REVIEW

**Comment by rroohhh** [comment]
currently blocked by #88

**Comment by anuejn** [comment]
we can continue, since usb works again :)

**Comment by anuejn** [comment]
tbd is a useful ap setup including a dhcp server and autostart.
maybe an axiom-wifi script is needed, that can switch between client and ap

**Comment by anuejn** [comment]
also redoing this pr as there is much unrelated stuff :(

**Pull request closed without merging**
