### PR TITLE
Paths fixed

### PR DESCRIPTION
**Pull request by kiquance21**
paths for rf_sel.py and pic_jtag_pcie.py fixed

### CODE REVIEW

**Comment by rroohhh** [comment]
thanks, we actually would want these two (`rf_sel.py` and `pic_jtag_pcie.py`) be moved to the `scripts` folder

**Comment by kiquance21** [comment]
` prep2.sh` in the `bringup-scripts` uses these file
Should I modify those then ?

**Comment by rroohhh** [comment]
nope, just adjust `prep2.sh` to the new path

the goal is to have every script that is used for normal operation in the `scripts` folder and all the scripts used for the factory setup and possible maintance in the `bringup-scripts` folder

**Comment by kiquance21** [comment]
By adjust do you mean move the file to `prep2.sh `to the `scripts` folder or modify the script itself,
as I see many scripts in which the path is incorrect in the `bringup-scripts folder`

**Comment by rroohhh** [comment]
I mean modify `prep2.sh`.

Yes you are right, most of the scripts in the `bringup-scripts` folder have not yet been adapted to the split between `scripts` and `bringup-scripts`

If you want to, feel free to tackle that.

**Pull request closed without merging**
