### PR TITLE
[Buildsystem] build rootfs in loopback to work around qemu bug

### PR DESCRIPTION
**Pull request by anuejn**

### CODE REVIEW

**Comment by anuejn** [comment]
Does anyone what the problem with the ci builds is?
I can build it locally.

cc @rroohhh @BAndiT1983

**Comment by BAndiT1983** [comment]
Looks like daemon build is failing, but it wasn't changed for quite some time. Maybe new CMake package is breaking stuff at the moment.

**Comment by rroohhh** [comment]
The error looks like the submodules are not getting downloaded correctly, but any attempt to verify that showed they are indeed initialized. So no clue.

I think we need to hack together a script again to ssh into the ci machine, i can't really think of anything better than that.

**Comment by rroohhh** [comment]
Also one thing that is really strange to me, is why cmake fails at the compiler identification, this should have nothing to do with the submodules and still fails. And this is in a arch linux arm chroot, which should be the same for local and CI builds in a docker container that is the same for a local and a CI build. So no clue what the fuck is going on.

**Comment by BAndiT1983** [comment]
Can't grab logs, as the task seems to run over and over, at least it's my impression, as the state is constantyl "Running".
Working on some other things, namely AXIOM Remote, so changing environment at the moment is not that possible. But if i can assist, then just let me know.

**Comment by BAndiT1983** [comment]
Can Ninja be the problem? Had some issues with CMake while testing it back then, but forgot what it was.

**Comment by rroohhh** [comment]
logs should be at https://cirrus-ci.com/task/6237517094846464?command=make#L8702

but the relevant part is also here https://paste.niemo.de/feyolexaha

**Comment by rroohhh** [comment]
> Can Ninja be the problem? Had some issues with CMake while testing it back then, but forgot what it was.

I don't think so, as `-- The C compiler identification is unknown` already seems pretty fishy and has nothing to do with ninja at all.

**Comment by BAndiT1983** [comment]
Hm, looks like it is missing the CXX_COMPILER variable -> https://stackoverflow.com/questions/9699930/cmake-complains-the-cxx-compiler-identification-is-unknown

**Comment by rroohhh** [comment]
ok so some debugging later and pretty sure this is the bug: https://bugs.launchpad.net/qemu/+bug/1805913

**Pull request merged**
