### PR TITLE
Add Wifi Hotspot functionality

### PR DESCRIPTION
**Pull request by anuejn**
This PR creates a passwordless WIFI Hotspot, when the camera has a wifi stick plugged in.

ssid: "axiom"
password: None

The camea has the ip 10.42.0.1 and it will be a dhcp & dns server. the domain axiom.camera will be resolved to this address.

A captive portal funcionality is implemented as follows:
All other domains will be resolved to 1.1.1.1. and all traffic to all adresses (except for 10.42.0.1) on port 80 will be redirected to 10.42.0.1:80 where a webserver will redirect to axiom.camera  
this allows the user to enter any ip and see the cameras webinterface. moreover most modern computers will show the cameras web ui imediately after connecting.

### CODE REVIEW

**Comment by rroohhh** [comment]
The kernel config changes seem to have some unrelated changes, is this intentional?

Have you thought about how a user would disable this?

Also maybe we should encourage / force users to setup a password for a wpa2 based wifi hotspot on the first access of the webui or something..

**Comment by anuejn** [comment]
> The kernel config changes seem to have some unrelated changes, is this intentional? (for example [these](https://github.com/apertus-open-source-cinema/axiom-beta-firmware/pull/122/files#diff-28a6d7c6b893d470f980c68a9b2b48f0R690-R691)).

Most of them are due to a new kernel and a new compiler afak?

> Have you thought about how a user would disable this?

They can simply disable the NetworkManager profile with nmcli or nmtui. everything else is dependent on these. 

> Also maybe we should encourage / force users to setup a password for a wpa2 based wifi hotspot on the first access of the webui or something...

Maybe, but maybe not now ;). I think this should be done by some webui ;)

**Comment by anuejn** [comment]
When @sp-apertus and @rroohhh give green light, we can merge this imho :)

**Comment by rroohhh** [comment]
> > The kernel config changes seem to have some unrelated changes, is this intentional? (for example [these](https://github.com/apertus-open-source-cinema/axiom-beta-firmware/pull/122/files#diff-28a6d7c6b893d470f980c68a9b2b48f0R690-R691)).
> 
> Most of them are due to a new kernel and a new compiler afaik?

ah yes could very well be
> 
> > Have you thought about how a user would disable this?
> 
> They can simply disable the NetworkManager profile with nmcli or nmtui. everything else is dependent on these.

perfect
> 
> > Also maybe we should encourage / force users to setup a password for a wpa2 based wifi hotspot on the first access of the webui or something...
> 
> Maybe, but maybe not now ;). I think this should be done by some webui ;)

yeah of course

**Comment by rroohhh** [comment]
Can't test it as I have no wifi stick on hand, but otherwise lgtm.

**Comment by anuejn** [comment]
Maybe we also want to experiment with usb-gadget networking for the micro a bit further, as this would improve the usability heavily.

Id vote for using a similiar NetworkManager profile there

**Comment by rroohhh** [comment]
Yes I like that idea, but I would say that should go into a different PR.

**Pull request merged**
